import { defineConfig } from 'orval';

// Generates typed React Query hooks from the OpenAPI schema produced by the Quarkus
// API. Regenerate with `pnpm --filter @librarius/web gen:api`.
export default defineConfig({
  librarius: {
    input: '../../openapi/openapi.json',
    output: {
      mode: 'single',
      target: './src/api/generated/librarius.ts',
      client: 'react-query',
      baseUrl: '',
      clean: true,
      override: {
        header: () => [
          'Generated by orval from openapi/openapi.json.',
          'DO NOT edit by hand — run `pnpm gen:api`.',
        ],
        fetch: { includeHttpResponseReturnType: false },
        query: {
          // No AbortSignal: jsdom produces signals that Node's fetch refuses, which
          // would make every request fail under test. Responses here are small JSON
          // payloads, so cancelling on unmount buys little.
          signal: false,
        },
        // Our own fetch-based client: it attaches the bearer token and renews an
        // expired session. Without it, orval's react-query client would pull in axios.
        mutator: {
          path: './src/shared/apiClient.ts',
          name: 'apiClient',
        },
      },
    },
  },
});
