apiVersion: v2
name: librarius
description: Ma Bibliothèque (Librarius) — stack complète (web + api + postgres + keycloak)
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/zelytra/Librarius
