/**
 * Every glyph baked into the self-hosted Material Symbols subset
 * (`shared/styles/fonts/material-symbols-subset.woff2`), generated by
 * `apps/web/scripts/generate-icon-font.mjs` from this exact table — see that script for
 * the full rationale (issue #161: the full Material Symbols font cost 407 kB to draw
 * about thirty icons).
 *
 * Each icon is addressed by its Private Use Area code point rather than by the ligature
 * name Material Symbols also supports (typing "arrow_back" and letting the font's GSUB
 * table substitute a glyph for it — what `Icon` used to render). Both addressing modes
 * resolve to the exact same glyph in Google's font: verified directly against the
 * downloaded font before switching, by shaping the ligature text and the code point
 * separately and comparing the resulting glyph ID. The code points are Google's own,
 * published per icon in the `.codepoints` file alongside every Material Symbols font
 * (see the script) — a stable identifier, not something this app invented.
 *
 * The switch matters for subsetting: hb-subset (used by `subset-font`) selects glyphs
 * by *closure* — keep every ligature reachable from the requested letters. With ~38
 * names spread across the alphabet that closure reaches a large fraction of the ~4200
 * icons in the font (a font subsetted to the 38 ligature names only came out 18%
 * smaller). Selecting by code point needs no closure at all: each one maps directly to
 * exactly one glyph, so the subset holds only the ~38 glyphs actually used.
 *
 * This table is the single source of truth on the front-end side: the generation script
 * reads it to decide which glyphs to keep, and `Icon` renders `String.fromCodePoint()`
 * of whatever this table maps `name` to — so a name missing from it cannot render
 * anything, and is guarded against below.
 *
 * Adding an icon:
 *   1. Look up its code point in Google's `.codepoints` file for Material Symbols
 *      Rounded (the script prints the URL) and add `name: 0x____` here (alphabetical,
 *      to make a missing/duplicate entry easy to spot).
 *   2. Run `pnpm --filter @librarius/web generate:icon-font` and commit the regenerated
 *      `.woff2` alongside the code that uses the icon.
 *   3. `pnpm web:test` renders every screen at least once, so the new usage is exercised
 *      — the guard in `Icon.tsx` only helps if something actually renders the icon.
 */
export const ICON_CODEPOINTS: Readonly<Record<string, number>> = {
  add: 0xe145,
  arrow_back: 0xe5c4,
  arrow_forward: 0xe5c8,
  auto_stories: 0xe666,
  book_2: 0xf53e,
  bookmark_add: 0xe598,
  bookmark_added: 0xe599,
  calendar_month: 0xebcc,
  check_circle: 0xf0be,
  chevron_right: 0xe5cc,
  close: 0xe5cd,
  cloud_off: 0xe2c1,
  collections_bookmark: 0xe431,
  cottage: 0xe587,
  delete: 0xe92e,
  delete_forever: 0xe92b,
  download: 0xf090,
  edit: 0xf097,
  expand_less: 0xe5ce,
  favorite: 0xe87e,
  flag: 0xf0c6,
  insights: 0xf092,
  keyboard_arrow_down: 0xe313,
  keyboard_arrow_up: 0xe316,
  library_books: 0xe02f,
  local_fire_department: 0xef55,
  lock: 0xe899,
  login: 0xea77,
  menu_book: 0xea19,
  military_tech: 0xea3f,
  priority_high: 0xe645,
  schedule: 0xefd6,
  search: 0xef7a,
  search_off: 0xea76,
  settings: 0xe8b8,
  shopping_bag: 0xf1cc,
  star: 0xf09a,
  table_view: 0xf1be,
  tune: 0xe429,
  upload_file: 0xe9fc,
  visibility: 0xe8f4,
  visibility_off: 0xe8f5,
  workspace_premium: 0xe7af,
};
